name: Android CI/CD - Release to Play Store

on:
  push:
    branches:
      - main # Or your release branch, e.g., 'release/*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Or your project's JDK version
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build aab
        run: ./gradlew bundleRelease # Or your specific bundle task

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        # Only if you're not using Google Play App Signing
        # and are signing the AAB yourself before upload.
        # If using Play App Signing (recommended), you can skip this
        # or ensure your bundleRelease task handles signing.
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        # This step is often handled by Google Play App Signing.
        # If you have Play App Signing enabled (which is the default and recommended),
        # Google Play will re-sign your app. In this case, you just need to upload
        # a signed AAB (often signed with an "upload key").

      - name: Upload AAB to Google Play
        uses: r0adkll/upload-google-play@v1.0.23 # Check for the latest version
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN_TEXT }}
          packageName: com.example.yourapp # Replace with your app's package name
          releaseFiles: app/build/outputs/bundle/release/*.aab # Path to your AAB
          track: internal # Or alpha, beta, production, internalappsharing
          # userFraction: 0.5 # For staged rollouts (e.g., 50%) - optional
          # whatsNewDirectory: whatsnew/ # Path to release notes (optional)
          # mappingFile: app/build/outputs/mapping/release/mapping.txt # Optional mapping file
          # debugSymbols: app/build/outputs/native-debug-symbols/release/*.zip # Optional native debug symbols
          # status: completed # Or 'draft', 'inProgress'